### ISSUE TITLE
Making this software citable

### ISSUE THREAD

**Issue by FrederikRiedel** [mimurrayy/COST-power-monitor#1]
Hi,
I think it would be cool to make this software citable by submitting a short paper to https://openresearchsoftware.metajnl.com .
Then it gets a DOI and the author some citations.

Have a nice day!

**Comment by Julian-Held** [comment]
Hi,
while I agree, that the software should be citable, this looks like a lot of work for a very niche product.
However, I know that there are some other places where a DOI can be assigned without needing to write an actual article. I will take a look at some of the options soon.

Cheers,
Julian

**Comment by Julian-Held** [comment]
The software can now be cited using the information found here:
http://doi.org/10.5281/zenodo.3538294
